### ISSUE TITLE
Formatação de posts no admin

### ISSUE THREAD

**Issue by gugaalves** [wp-rio/wp-rio#123]
Não sei o que foi feito no CSS criado por nós mas a formatação dos posts no back-end foi quebrada. Criei um H2 na aba visual de um post e ele aparece como se fosse um parágrafo, acaba atrapalhando a revisão das matérias.

**Comment by gugaalves** [comment]
@theandersonn o arquivo /wp-content/themes/wp-rio/assets/sass/bootstrap/bootstrap/_type.scss está sendo carregado no back-end alterando o que falei, pode dar uma olhada depois?
Marquei os demais também, quem quiser resolver é só se manifestar :D

**Comment by theandersonn** [comment]
Olhei rapidamente e sim é alguma coisa com o '_type', assim que possivel vou ver, provavelmente algo com os imports.

**Comment by rodrigocka** [comment]
Não sei se entendi o problema @gugaalves, mas não seria porque o Odin carrega as classes do bootstrap para a tela de edição dos posts?
No arquivo functions.php (128), Odin carrega o arquivo `assets/css/editor-style.css`, que é a versão compilada do `assets/sass/editor-style.scss`:

``` scss
// ==========================================================================
// Style used to style the TinyMCE editor
// ==========================================================================

@import
        "variables",           // Theme       Custom Variables
        "bootstrap/bootstrap", // Bootstrap   Styles Core
        "wordpress/wordpress"  // WordPress   Styles Core
;

// Custom Editor Styles
// ==========================================================================
body {
    padding: 10px;
}
```
